-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/A54YeHpVNJqqzV+
ohDQD7qe16ydV7FL8tO6cKFtPcCgCgYIKoZIzj0DAQehRANCAASut9OlZQLEEQMl
q8tLXm1PpUp0ppllNpJgitltgZ76Il2YGzZyimXTLKxXYyuLEbELHwzfuzEYxA0Y
DIdMr3sn
-----END PRIVATE KEY-----